/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/assets/new_surface_study_2.glb 
Author: tamminen (https://sketchfab.com/tamminen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/new-surface-study-2-4e821134e2994b8d8164dd7255fe9fd6
Title: New Surface study 2
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('new_surface_study_2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Icosphere_0">
                <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Icosphere001_1" rotation={[0.642, 0.57, 0.814]} scale={0.979}>
                <mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Icosphere002_2" rotation={[0.118, -0.138, -0.298]} scale={0.954}>
                <mesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Icosphere003_3" rotation={[0.846, 0.275, 0.657]} scale={0.934}>
                <mesh name="mesh_3" geometry={nodes.mesh_3.geometry} material={materials['Scene_-_Root']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('new_surface_study_2.glb')